In [1]:
import pandas as pd
from scipy import spatial
import numpy as np

In [2]:
df=pd.read_csv('C:\\Users\\Owen\\Desktop\\pmp\\Topic2_4470_Word_Vectors.csv',header=None,sep=',')


In [3]:
df


0         1         2         3         4         5    \
0                      ? -0.014292  0.007838 -0.002896  0.007041  0.009640   
1                      ? -0.019124  0.004895  0.000261 -0.002996  0.004262   
2                      ? -0.015925  0.008959  0.012728  0.001627  0.009002   
3                     ''  0.242879 -0.357776 -1.036951  0.469952 -1.611660   
4               proyecto  0.006645  0.002655 -0.002004  0.011898  0.009993   
...                  ...       ...       ...       ...       ...       ...   
49346                1.9 -0.002337  0.002169 -0.015479  0.009018 -0.012332   
49347    ceramic-polymer -0.015645  0.027500  0.015190  0.001908  0.000280   
49348       tape-casting -0.035595  0.022825 -0.005805  0.004398 -0.009485   
49349          disc-type -0.058460  0.017930 -0.020420 -0.003634 -0.013074   
49350  multilayered-type -0.054010  0.014619 -0.017170  0.005641 -0.005823   

            6         7         8         9    ...       91        92   \
0      0.000983  0.005310  0.001771  0.005891  ... -0.001305 -0.001553   
1      0.007593 -0.008057  0.016138  0.009148  ... -0.004555  0.008343   
2     -0.009196  0.000113  0.014790  0.001011  ...  0.005379 -0.000023   
3     -0.920393 -1.047843  0.812955  0.077639  ...  0.014267 -0.450508   
4     -0.003337 -0.017918  0.001710  0.001841  ...  0.001581  0.004362   
...         ...       ...       ...       ...  ...       ...       ...   
49346 -0.005880 -0.001747 -0.015124 -0.000619  ... -0.009729 -0.007291   
49347 -0.001888  0.004398  0.010840  0.003353  ... -0.007756 -0.011556   
49348 -0.004525 -0.005787  0.019662  0.010332  ... -0.010189 -0.011675   
49349 -0.009637  0.006483  0.024382  0.010641  ... -0.019693 -0.009310   
49350  0.001231  0.007013  0.018517  0.011593  ... -0.012833 -0.010574   

            93        94        95        96        97        98        99   \
0     -0.014225  0.002071 -0.023745 -0.005997 -0.003445 -0.024899  0.017323   
1     -0.014806 -0.012592 -0.020747 -0.007772  0.000497 -0.021847  0.021408   
2     -0.007696 -0.004017 -0.019730 -0.013710  0.004691 -0.028078  0.021047   
3     -0.778890  0.135372  0.134435 -0.894964  0.506059 -1.636131  1.420139   
4     -0.014756 -0.015226 -0.023745 -0.009586 -0.014421 -0.004782  0.034854   
...         ...       ...       ...       ...       ...       ...       ...   
49346 -0.004602  0.009725  0.012778  0.003016 -0.001009 -0.031664 -0.003349   
49347 -0.001872  0.004398 -0.009889 -0.000199 -0.004234 -0.014100  0.006598   
49348 -0.012465  0.002276 -0.001751 -0.007735  0.009182 -0.042329  0.036488   
49349 -0.036355  0.006278 -0.007550 -0.006744  0.019674 -0.064233  0.038439   
49350 -0.030285  0.002189 -0.013837  0.002057  0.002176 -0.057600  0.035376   

            100  
0     -0.002442  
1     -0.009102  
2      0.000338  
3     -1.053915  
4      0.013337  
...         ...  
49346 -0.005023  
49347  0.004098  
49348 -0.005002  
49349 -0.016577  
49350 -0.013578  

[49351 rows x 101 columns]

In [4]:
new_df = df.loc[:, df.columns != 0]

In [5]:
new_df

1         2         3         4         5         6         7    \
0     -0.014292  0.007838 -0.002896  0.007041  0.009640  0.000983  0.005310   
1     -0.019124  0.004895  0.000261 -0.002996  0.004262  0.007593 -0.008057   
2     -0.015925  0.008959  0.012728  0.001627  0.009002 -0.009196  0.000113   
3      0.242879 -0.357776 -1.036951  0.469952 -1.611660 -0.920393 -1.047843   
4      0.006645  0.002655 -0.002004  0.011898  0.009993 -0.003337 -0.017918   
...         ...       ...       ...       ...       ...       ...       ...   
49346 -0.002337  0.002169 -0.015479  0.009018 -0.012332 -0.005880 -0.001747   
49347 -0.015645  0.027500  0.015190  0.001908  0.000280 -0.001888  0.004398   
49348 -0.035595  0.022825 -0.005805  0.004398 -0.009485 -0.004525 -0.005787   
49349 -0.058460  0.017930 -0.020420 -0.003634 -0.013074 -0.009637  0.006483   
49350 -0.054010  0.014619 -0.017170  0.005641 -0.005823  0.001231  0.007013   

            8         9         10   ...       91        92        93   \
0      0.001771  0.005891  0.012021  ... -0.001305 -0.001553 -0.014225   
1      0.016138  0.009148  0.013248  ... -0.004555  0.008343 -0.014806   
2      0.014790  0.001011  0.016847  ...  0.005379 -0.000023 -0.007696   
3      0.812955  0.077639  0.406976  ...  0.014267 -0.450508 -0.778890   
4      0.001710  0.001841  0.021023  ...  0.001581  0.004362 -0.014756   
...         ...       ...       ...  ...       ...       ...       ...   
49346 -0.015124 -0.000619  0.001248  ... -0.009729 -0.007291 -0.004602   
49347  0.010840  0.003353  0.003227  ... -0.007756 -0.011556 -0.001872   
49348  0.019662  0.010332  0.004159  ... -0.010189 -0.011675 -0.012465   
49349  0.024382  0.010641  0.008010  ... -0.019693 -0.009310 -0.036355   
49350  0.018517  0.011593  0.013623  ... -0.012833 -0.010574 -0.030285   

            94        95        96        97        98        99        100  
0      0.002071 -0.023745 -0.005997 -0.003445 -0.024899  0.017323 -0.002442  
1     -0.012592 -0.020747 -0.007772  0.000497 -0.021847  0.021408 -0.009102  
2     -0.004017 -0.019730 -0.013710  0.004691 -0.028078  0.021047  0.000338  
3      0.135372  0.134435 -0.894964  0.506059 -1.636131  1.420139 -1.053915  
4     -0.015226 -0.023745 -0.009586 -0.014421 -0.004782  0.034854  0.013337  
...         ...       ...       ...       ...       ...       ...       ...  
49346  0.009725  0.012778  0.003016 -0.001009 -0.031664 -0.003349 -0.005023  
49347  0.004398 -0.009889 -0.000199 -0.004234 -0.014100  0.006598  0.004098  
49348  0.002276 -0.001751 -0.007735  0.009182 -0.042329  0.036488 -0.005002  
49349  0.006278 -0.007550 -0.006744  0.019674 -0.064233  0.038439 -0.016577  
49350  0.002189 -0.013837  0.002057  0.002176 -0.057600  0.035376 -0.013578  

[49351 rows x 100 columns]

In [6]:
from sklearn.metrics.pairwise import cosine_similarity
cos_sim=cosine_similarity(new_df)

In [16]:
cos_sim

array([[1.        , 0.87995355, 0.88515485, ..., 0.7508843 , 0.72637594,
        0.79651789],
       [0.87995355, 1.        , 0.84421838, ..., 0.73819506, 0.72731827,
        0.77602114],
       [0.88515485, 0.84421838, 1.        , ..., 0.75335583, 0.72131693,
        0.77981015],
       ...,
       [0.7508843 , 0.73819506, 0.75335583, ..., 1.        , 0.92937995,
        0.9282302 ],
       [0.72637594, 0.72731827, 0.72131693, ..., 0.92937995, 1.        ,
        0.96511994],
       [0.79651789, 0.77602114, 0.77981015, ..., 0.9282302 , 0.96511994,
        1.        ]])

In [14]:
cos_sim.shape

(49351, 49351)

In [48]:
import math
#euclidean
npvec1, npvec2 = np.array(new_df.iloc[0]), np.array(new_df.iloc[1])
similirity=math.sqrt(((npvec1 - npvec2) ** 2).sum())
print('similirity:',similirity)

similirity: 0.07424949786336761


In [51]:
 #cossin 
def cos_sim(vector_a, vector_b):

    vector_a = np.mat(vector_a)
    vector_b = np.mat(vector_b)
    num = float(vector_a * vector_b.T)
    denom = np.linalg.norm(vector_a) * np.linalg.norm(vector_b)
    cos = num / denom #
    sim = 0.5 + 0.5 * cos # put the cos into range of [-1,1]
    return sim
 

vector_a, vector_b = np.array(new_df.iloc[0]), np.array(new_df.iloc[1])
similirity2=cos_sim(vector_a, vector_b)
print('similirity2:',similirity2)

similirity2: 0.9399767768081573


In [26]:
new_df

1         2         3         4         5         6         7    \
0     -0.014292  0.007838 -0.002896  0.007041  0.009640  0.000983  0.005310   
1     -0.019124  0.004895  0.000261 -0.002996  0.004262  0.007593 -0.008057   
2     -0.015925  0.008959  0.012728  0.001627  0.009002 -0.009196  0.000113   
3      0.242879 -0.357776 -1.036951  0.469952 -1.611660 -0.920393 -1.047843   
4      0.006645  0.002655 -0.002004  0.011898  0.009993 -0.003337 -0.017918   
...         ...       ...       ...       ...       ...       ...       ...   
49346 -0.002337  0.002169 -0.015479  0.009018 -0.012332 -0.005880 -0.001747   
49347 -0.015645  0.027500  0.015190  0.001908  0.000280 -0.001888  0.004398   
49348 -0.035595  0.022825 -0.005805  0.004398 -0.009485 -0.004525 -0.005787   
49349 -0.058460  0.017930 -0.020420 -0.003634 -0.013074 -0.009637  0.006483   
49350 -0.054010  0.014619 -0.017170  0.005641 -0.005823  0.001231  0.007013   

            8         9         10   ...       91        92        93   \
0      0.001771  0.005891  0.012021  ... -0.001305 -0.001553 -0.014225   
1      0.016138  0.009148  0.013248  ... -0.004555  0.008343 -0.014806   
2      0.014790  0.001011  0.016847  ...  0.005379 -0.000023 -0.007696   
3      0.812955  0.077639  0.406976  ...  0.014267 -0.450508 -0.778890   
4      0.001710  0.001841  0.021023  ...  0.001581  0.004362 -0.014756   
...         ...       ...       ...  ...       ...       ...       ...   
49346 -0.015124 -0.000619  0.001248  ... -0.009729 -0.007291 -0.004602   
49347  0.010840  0.003353  0.003227  ... -0.007756 -0.011556 -0.001872   
49348  0.019662  0.010332  0.004159  ... -0.010189 -0.011675 -0.012465   
49349  0.024382  0.010641  0.008010  ... -0.019693 -0.009310 -0.036355   
49350  0.018517  0.011593  0.013623  ... -0.012833 -0.010574 -0.030285   

            94        95        96        97        98        99        100  
0      0.002071 -0.023745 -0.005997 -0.003445 -0.024899  0.017323 -0.002442  
1     -0.012592 -0.020747 -0.007772  0.000497 -0.021847  0.021408 -0.009102  
2     -0.004017 -0.019730 -0.013710  0.004691 -0.028078  0.021047  0.000338  
3      0.135372  0.134435 -0.894964  0.506059 -1.636131  1.420139 -1.053915  
4     -0.015226 -0.023745 -0.009586 -0.014421 -0.004782  0.034854  0.013337  
...         ...       ...       ...       ...       ...       ...       ...  
49346  0.009725  0.012778  0.003016 -0.001009 -0.031664 -0.003349 -0.005023  
49347  0.004398 -0.009889 -0.000199 -0.004234 -0.014100  0.006598  0.004098  
49348  0.002276 -0.001751 -0.007735  0.009182 -0.042329  0.036488 -0.005002  
49349  0.006278 -0.007550 -0.006744  0.019674 -0.064233  0.038439 -0.016577  
49350  0.002189 -0.013837  0.002057  0.002176 -0.057600  0.035376 -0.013578  

[49351 rows x 100 columns]

In [37]:
np.array(new_df.iloc[0])

array([-0.01429176,  0.00783814, -0.00289604,  0.00704056,  0.00963996,
        0.00098287,  0.00530974,  0.00177137,  0.00589055,  0.01202077,
        0.01353311, -0.01012663, -0.01145114, -0.00300807,  0.00484793,
        0.01468758, -0.00632745,  0.01841349, -0.00286759,  0.00635551,
        0.00125448, -0.02434577,  0.01166061, -0.01969153,  0.00760905,
       -0.00337474,  0.00502301, -0.01345061, -0.00675768,  0.00861691,
       -0.00768818,  0.00508589, -0.01337041,  0.0109017 ,  0.01663519,
       -0.01060985,  0.00208496, -0.00237974, -0.00150775,  0.0100626 ,
        0.00657779, -0.00020292,  0.01053251,  0.00091423,  0.01046894,
        0.00384944,  0.00752203,  0.00870534, -0.00065664, -0.00157549,
       -0.00153631,  0.00907322, -0.01248736, -0.01021067,  0.00585567,
       -0.00153286,  0.01902578, -0.00067022,  0.00660779,  0.00930715,
       -0.01536092,  0.01125728,  0.0221387 ,  0.00728419, -0.0012706 ,
       -0.001952  , -0.00565638,  0.01407096,  0.02338489,  0.01

In [4]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
en_stops = stopwords.words('english')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Owen\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [5]:
en_stops.extend([':','A','The',')','(','An','via',',','using','Small','Medium','Large','?',';','in','many','.','>',
                '<','br/','This','including','also','one','two','use','Use','Research','\'','\"'])

In [6]:
en_stops

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [7]:
df


0         1         2         3         4         5    \
0                      ? -0.014292  0.007838 -0.002896  0.007041  0.009640   
1                      ? -0.019124  0.004895  0.000261 -0.002996  0.004262   
2                      ? -0.015925  0.008959  0.012728  0.001627  0.009002   
3                     ''  0.242879 -0.357776 -1.036951  0.469952 -1.611660   
4               proyecto  0.006645  0.002655 -0.002004  0.011898  0.009993   
...                  ...       ...       ...       ...       ...       ...   
49346                1.9 -0.002337  0.002169 -0.015479  0.009018 -0.012332   
49347    ceramic-polymer -0.015645  0.027500  0.015190  0.001908  0.000280   
49348       tape-casting -0.035595  0.022825 -0.005805  0.004398 -0.009485   
49349          disc-type -0.058460  0.017930 -0.020420 -0.003634 -0.013074   
49350  multilayered-type -0.054010  0.014619 -0.017170  0.005641 -0.005823   

            6         7         8         9    ...       91        92   \
0      0.000983  0.005310  0.001771  0.005891  ... -0.001305 -0.001553   
1      0.007593 -0.008057  0.016138  0.009148  ... -0.004555  0.008343   
2     -0.009196  0.000113  0.014790  0.001011  ...  0.005379 -0.000023   
3     -0.920393 -1.047843  0.812955  0.077639  ...  0.014267 -0.450508   
4     -0.003337 -0.017918  0.001710  0.001841  ...  0.001581  0.004362   
...         ...       ...       ...       ...  ...       ...       ...   
49346 -0.005880 -0.001747 -0.015124 -0.000619  ... -0.009729 -0.007291   
49347 -0.001888  0.004398  0.010840  0.003353  ... -0.007756 -0.011556   
49348 -0.004525 -0.005787  0.019662  0.010332  ... -0.010189 -0.011675   
49349 -0.009637  0.006483  0.024382  0.010641  ... -0.019693 -0.009310   
49350  0.001231  0.007013  0.018517  0.011593  ... -0.012833 -0.010574   

            93        94        95        96        97        98        99   \
0     -0.014225  0.002071 -0.023745 -0.005997 -0.003445 -0.024899  0.017323   
1     -0.014806 -0.012592 -0.020747 -0.007772  0.000497 -0.021847  0.021408   
2     -0.007696 -0.004017 -0.019730 -0.013710  0.004691 -0.028078  0.021047   
3     -0.778890  0.135372  0.134435 -0.894964  0.506059 -1.636131  1.420139   
4     -0.014756 -0.015226 -0.023745 -0.009586 -0.014421 -0.004782  0.034854   
...         ...       ...       ...       ...       ...       ...       ...   
49346 -0.004602  0.009725  0.012778  0.003016 -0.001009 -0.031664 -0.003349   
49347 -0.001872  0.004398 -0.009889 -0.000199 -0.004234 -0.014100  0.006598   
49348 -0.012465  0.002276 -0.001751 -0.007735  0.009182 -0.042329  0.036488   
49349 -0.036355  0.006278 -0.007550 -0.006744  0.019674 -0.064233  0.038439   
49350 -0.030285  0.002189 -0.013837  0.002057  0.002176 -0.057600  0.035376   

            100  
0     -0.002442  
1     -0.009102  
2      0.000338  
3     -1.053915  
4      0.013337  
...         ...  
49346 -0.005023  
49347  0.004098  
49348 -0.005002  
49349 -0.016577  
49350 -0.013578  

[49351 rows x 101 columns]

In [8]:
df.drop(df.index[df[0].isin(en_stops)], inplace = True)

In [9]:
df

0         1         2         3         4         5    \
3                     ''  0.242879 -0.357776 -1.036951  0.469952 -1.611660   
4               proyecto  0.006645  0.002655 -0.002004  0.011898  0.009993   
5                 hombre -0.013173  0.005983  0.002263  0.010255  0.002010   
6                     30 -0.908531 -0.033861 -0.124413 -0.316041  0.550499   
7                  years -0.991988 -0.052203 -0.746462  0.054751  0.091673   
...                  ...       ...       ...       ...       ...       ...   
49346                1.9 -0.002337  0.002169 -0.015479  0.009018 -0.012332   
49347    ceramic-polymer -0.015645  0.027500  0.015190  0.001908  0.000280   
49348       tape-casting -0.035595  0.022825 -0.005805  0.004398 -0.009485   
49349          disc-type -0.058460  0.017930 -0.020420 -0.003634 -0.013074   
49350  multilayered-type -0.054010  0.014619 -0.017170  0.005641 -0.005823   

            6         7         8         9    ...       91        92   \
3     -0.920393 -1.047843  0.812955  0.077639  ...  0.014267 -0.450508   
4     -0.003337 -0.017918  0.001710  0.001841  ...  0.001581  0.004362   
5     -0.004880 -0.009383  0.012091 -0.008488  ...  0.005712  0.005137   
6     -0.068102  0.063906  0.945967 -0.010683  ... -0.064064  0.185626   
7      0.003364  0.058668  1.027198 -0.095780  ...  0.173858  0.079364   
...         ...       ...       ...       ...  ...       ...       ...   
49346 -0.005880 -0.001747 -0.015124 -0.000619  ... -0.009729 -0.007291   
49347 -0.001888  0.004398  0.010840  0.003353  ... -0.007756 -0.011556   
49348 -0.004525 -0.005787  0.019662  0.010332  ... -0.010189 -0.011675   
49349 -0.009637  0.006483  0.024382  0.010641  ... -0.019693 -0.009310   
49350  0.001231  0.007013  0.018517  0.011593  ... -0.012833 -0.010574   

            93        94        95        96        97        98        99   \
3     -0.778890  0.135372  0.134435 -0.894964  0.506059 -1.636131  1.420139   
4     -0.014756 -0.015226 -0.023745 -0.009586 -0.014421 -0.004782  0.034854   
5     -0.010636 -0.022955 -0.031071 -0.000086 -0.003307 -0.012513  0.032919   
6     -0.287499  0.059508  0.060407  0.128885  0.751422 -0.356749  0.473993   
7     -0.340901  0.004598  0.866518 -0.039558  0.529889 -0.528149  0.582073   
...         ...       ...       ...       ...       ...       ...       ...   
49346 -0.004602  0.009725  0.012778  0.003016 -0.001009 -0.031664 -0.003349   
49347 -0.001872  0.004398 -0.009889 -0.000199 -0.004234 -0.014100  0.006598   
49348 -0.012465  0.002276 -0.001751 -0.007735  0.009182 -0.042329  0.036488   
49349 -0.036355  0.006278 -0.007550 -0.006744  0.019674 -0.064233  0.038439   
49350 -0.030285  0.002189 -0.013837  0.002057  0.002176 -0.057600  0.035376   

            100  
3     -1.053915  
4      0.013337  
5      0.008704  
6     -0.148028  
7     -0.154103  
...         ...  
49346 -0.005023  
49347  0.004098  
49348 -0.005002  
49349 -0.016577  
49350 -0.013578  

[49197 rows x 101 columns]

In [11]:
get_df= pd.to_numeric(df[0],errors='coerce')

In [14]:
df[0]

3                       ''
4                 proyecto
5                   hombre
6                       30
7                    years
               ...        
49346                  1.9
49347      ceramic-polymer
49348         tape-casting
49349            disc-type
49350    multilayered-type
Name: 0, Length: 49197, dtype: object

In [13]:
df

0         1         2         3         4         5    \
3                     ''  0.242879 -0.357776 -1.036951  0.469952 -1.611660   
4               proyecto  0.006645  0.002655 -0.002004  0.011898  0.009993   
5                 hombre -0.013173  0.005983  0.002263  0.010255  0.002010   
6                     30 -0.908531 -0.033861 -0.124413 -0.316041  0.550499   
7                  years -0.991988 -0.052203 -0.746462  0.054751  0.091673   
...                  ...       ...       ...       ...       ...       ...   
49346                1.9 -0.002337  0.002169 -0.015479  0.009018 -0.012332   
49347    ceramic-polymer -0.015645  0.027500  0.015190  0.001908  0.000280   
49348       tape-casting -0.035595  0.022825 -0.005805  0.004398 -0.009485   
49349          disc-type -0.058460  0.017930 -0.020420 -0.003634 -0.013074   
49350  multilayered-type -0.054010  0.014619 -0.017170  0.005641 -0.005823   

            6         7         8         9    ...       91        92   \
3     -0.920393 -1.047843  0.812955  0.077639  ...  0.014267 -0.450508   
4     -0.003337 -0.017918  0.001710  0.001841  ...  0.001581  0.004362   
5     -0.004880 -0.009383  0.012091 -0.008488  ...  0.005712  0.005137   
6     -0.068102  0.063906  0.945967 -0.010683  ... -0.064064  0.185626   
7      0.003364  0.058668  1.027198 -0.095780  ...  0.173858  0.079364   
...         ...       ...       ...       ...  ...       ...       ...   
49346 -0.005880 -0.001747 -0.015124 -0.000619  ... -0.009729 -0.007291   
49347 -0.001888  0.004398  0.010840  0.003353  ... -0.007756 -0.011556   
49348 -0.004525 -0.005787  0.019662  0.010332  ... -0.010189 -0.011675   
49349 -0.009637  0.006483  0.024382  0.010641  ... -0.019693 -0.009310   
49350  0.001231  0.007013  0.018517  0.011593  ... -0.012833 -0.010574   

            93        94        95        96        97        98        99   \
3     -0.778890  0.135372  0.134435 -0.894964  0.506059 -1.636131  1.420139   
4     -0.014756 -0.015226 -0.023745 -0.009586 -0.014421 -0.004782  0.034854   
5     -0.010636 -0.022955 -0.031071 -0.000086 -0.003307 -0.012513  0.032919   
6     -0.287499  0.059508  0.060407  0.128885  0.751422 -0.356749  0.473993   
7     -0.340901  0.004598  0.866518 -0.039558  0.529889 -0.528149  0.582073   
...         ...       ...       ...       ...       ...       ...       ...   
49346 -0.004602  0.009725  0.012778  0.003016 -0.001009 -0.031664 -0.003349   
49347 -0.001872  0.004398 -0.009889 -0.000199 -0.004234 -0.014100  0.006598   
49348 -0.012465  0.002276 -0.001751 -0.007735  0.009182 -0.042329  0.036488   
49349 -0.036355  0.006278 -0.007550 -0.006744  0.019674 -0.064233  0.038439   
49350 -0.030285  0.002189 -0.013837  0.002057  0.002176 -0.057600  0.035376   

            100  
3     -1.053915  
4      0.013337  
5      0.008704  
6     -0.148028  
7     -0.154103  
...         ...  
49346 -0.005023  
49347  0.004098  
49348 -0.005002  
49349 -0.016577  
49350 -0.013578  

[49197 rows x 101 columns]

In [25]:
bool_series = pd.notnull(get_df) 
bool_series


3        False
4        False
5        False
6         True
7        False
         ...  
49346     True
49347    False
49348    False
49349    False
49350    False
Name: 0, Length: 49197, dtype: bool

In [28]:
df[bool_series]

0         1         2         3         4         5         6    \
6          30 -0.908531 -0.033861 -0.124413 -0.316041  0.550499 -0.068102   
17       2015 -0.368581 -0.188758 -0.178032  0.041550  0.180337 -0.055289   
20         25 -0.467297 -0.114319 -0.149865 -0.026322  0.291353 -0.068272   
96        278 -0.023828 -0.020038 -0.017771 -0.007862 -0.010955 -0.002218   
128        23  0.024488 -0.002232 -0.001714  0.021488  0.011271 -0.014693   
...       ...       ...       ...       ...       ...       ...       ...   
49315  188.14 -0.011424 -0.004595 -0.004161  0.000896  0.017243 -0.000419   
49316   42.82 -0.012807 -0.013291  0.000401  0.002789  0.009485  0.004123   
49321    1.87  0.003267 -0.004160 -0.002333 -0.009973  0.014447  0.000163   
49344    5737  0.003993  0.009449  0.012774  0.014258  0.008403  0.006635   
49346     1.9 -0.002337  0.002169 -0.015479  0.009018 -0.012332 -0.005880   

            7         8         9    ...       91        92        93   \
6      0.063906  0.945967 -0.010683  ... -0.064064  0.185626 -0.287499   
17    -0.047721  0.315974  0.061549  ... -0.070776 -0.123311 -0.125246   
20     0.017396  0.481855 -0.045406  ...  0.008336  0.127144 -0.198767   
96    -0.012407  0.021379  0.003860  ... -0.000558  0.010200 -0.009436   
128   -0.009507 -0.008287  0.000476  ...  0.006840 -0.013334  0.006995   
...         ...       ...       ...  ...       ...       ...       ...   
49315  0.010767  0.009314  0.007421  ...  0.001385 -0.006476  0.000448   
49316 -0.001253  0.008915 -0.000658  ...  0.002810 -0.001942  0.001188   
49321 -0.005596  0.008476 -0.004654  ...  0.006516  0.002285  0.002840   
49344 -0.019113  0.000743 -0.005697  ... -0.004384 -0.003152 -0.014007   
49346 -0.001747 -0.015124 -0.000619  ... -0.009729 -0.007291 -0.004602   

            94        95        96        97        98        99        100  
6      0.059508  0.060407  0.128885  0.751422 -0.356749  0.473993 -0.148028  
17    -0.134654  0.005734  0.080504  0.052312 -0.254406  0.280104  0.006660  
20     0.003422  0.060191  0.084261  0.343665 -0.190612  0.259904 -0.049848  
96     0.003025 -0.005081  0.006926  0.025414 -0.018420  0.011780  0.004918  
128    0.005234  0.013535  0.001763  0.005122 -0.003292  0.000789  0.007377  
...         ...       ...       ...       ...       ...       ...       ...  
49315  0.009714  0.002485 -0.000609  0.003306 -0.019182  0.006983 -0.011256  
49316 -0.000956  0.003437  0.002333  0.012245 -0.008363  0.001926 -0.002123  
49321  0.001778  0.006985  0.003600  0.006292 -0.001922 -0.002481 -0.010620  
49344  0.005720  0.010350 -0.004214 -0.003116 -0.011364  0.011050  0.001171  
49346  0.009725  0.012778  0.003016 -0.001009 -0.031664 -0.003349 -0.005023  

[2197 rows x 101 columns]

In [ ]:
################Example

In [29]:
df.drop(df.index[df[0].isin(df[bool_series][0])], inplace = True)

In [30]:
df

0         1         2         3         4         5    \
3                        ''  0.242879 -0.357776 -1.036951  0.469952 -1.611660   
4                  proyecto  0.006645  0.002655 -0.002004  0.011898  0.009993   
5                    hombre -0.013173  0.005983  0.002263  0.010255  0.002010   
7                     years -0.991988 -0.052203 -0.746462  0.054751  0.091673   
9                      work -1.714099  0.291870 -0.900320  1.186268 -1.400966   
...                     ...       ...       ...       ...       ...       ...   
49345  magneto-photocurrent  0.000772 -0.005020 -0.001443  0.014552  0.004731   
49347       ceramic-polymer -0.015645  0.027500  0.015190  0.001908  0.000280   
49348          tape-casting -0.035595  0.022825 -0.005805  0.004398 -0.009485   
49349             disc-type -0.058460  0.017930 -0.020420 -0.003634 -0.013074   
49350     multilayered-type -0.054010  0.014619 -0.017170  0.005641 -0.005823   

            6         7         8         9    ...       91        92   \
3     -0.920393 -1.047843  0.812955  0.077639  ...  0.014267 -0.450508   
4     -0.003337 -0.017918  0.001710  0.001841  ...  0.001581  0.004362   
5     -0.004880 -0.009383  0.012091 -0.008488  ...  0.005712  0.005137   
7      0.003364  0.058668  1.027198 -0.095780  ...  0.173858  0.079364   
9      0.459634  0.394019 -0.358624 -0.434260  ... -0.344437 -0.572115   
...         ...       ...       ...       ...  ...       ...       ...   
49345 -0.003609 -0.009770 -0.002167 -0.013751  ... -0.003411 -0.002718   
49347 -0.001888  0.004398  0.010840  0.003353  ... -0.007756 -0.011556   
49348 -0.004525 -0.005787  0.019662  0.010332  ... -0.010189 -0.011675   
49349 -0.009637  0.006483  0.024382  0.010641  ... -0.019693 -0.009310   
49350  0.001231  0.007013  0.018517  0.011593  ... -0.012833 -0.010574   

            93        94        95        96        97        98        99   \
3     -0.778890  0.135372  0.134435 -0.894964  0.506059 -1.636131  1.420139   
4     -0.014756 -0.015226 -0.023745 -0.009586 -0.014421 -0.004782  0.034854   
5     -0.010636 -0.022955 -0.031071 -0.000086 -0.003307 -0.012513  0.032919   
7     -0.340901  0.004598  0.866518 -0.039558  0.529889 -0.528149  0.582073   
9     -0.702981  0.036555  0.382482  0.830119 -0.537139 -0.581230  0.365941   
...         ...       ...       ...       ...       ...       ...       ...   
49345 -0.018247  0.006264  0.004802 -0.003425  0.002871 -0.024917  0.007310   
49347 -0.001872  0.004398 -0.009889 -0.000199 -0.004234 -0.014100  0.006598   
49348 -0.012465  0.002276 -0.001751 -0.007735  0.009182 -0.042329  0.036488   
49349 -0.036355  0.006278 -0.007550 -0.006744  0.019674 -0.064233  0.038439   
49350 -0.030285  0.002189 -0.013837  0.002057  0.002176 -0.057600  0.035376   

            100  
3     -1.053915  
4      0.013337  
5      0.008704  
7     -0.154103  
9     -0.295305  
...         ...  
49345  0.003142  
49347  0.004098  
49348 -0.005002  
49349 -0.016577  
49350 -0.013578  

[47000 rows x 101 columns]

In [35]:
import re
def preprocess(raw_text):

    # keep only words
    letters_only_text = re.sub("[^a-zA-Z]", " ", raw_text)

    # convert to lower case and split 
    words = letters_only_text.lower().split()

    # remove stopwords
    stopword_set = set(stopwords.words("english"))
    cleaned_words = list(set([w for w in words if w not in stopword_set]))

    return cleaned_words


In [96]:
preprocess("hello guys")

['hello', 'guys']

In [40]:


gloveFile = "C:\\Users\\Owen\\Desktop\\AI_capstone\\glove.6B.50d.txt"
import numpy as np
def loadGloveModel(gloveFile):
    print ("Loading Glove Model")
    with open(gloveFile, encoding="utf8" ) as f:
        content = f.readlines()
    model = {}
    for line in content:
        splitLine = line.split()
        word = splitLine[0]
        embedding = np.array([float(val) for val in splitLine[1:]])
        model[word] = embedding
    print ("Done.",len(model)," words loaded!")
    return model


In [93]:
def cosine_distance_wordembedding_method(s1, s2):
    import scipy
    vector_1 = np.mean([model[word] for word in preprocess(s1)],axis=0)
    print(vector_1)
    vector_2 = np.mean([model[word] for word in preprocess(s2)],axis=0)
    print(vector_2)
    cosine = scipy.spatial.distance.cosine(vector_1, vector_2)
    print('Word Embedding method with a cosine distance asses that our two sentences are similar to',round((1-cosine)*100,2),'%')


In [41]:
model = loadGloveModel(gloveFile)

Loading Glove Model
Done. 400000  words loaded!


In [94]:
s1="Hello, world"
s2="Hi, world"
test=preprocess(s1)
cosine_distance_wordembedding_method(s1, s2)

[-3.999150e-01  7.597000e-01 -1.201970e-01  2.954500e-01  9.882550e-02
 -4.551000e-01 -5.090950e-01 -2.826500e-01  1.404500e-01  2.194200e-01
  3.288735e-01  3.987600e-01 -3.585900e-01  5.381550e-01  1.024800e+00
 -1.412195e-01 -6.614000e-02  5.867300e-01 -5.714700e-01 -1.098525e-01
 -4.170850e-02  2.911685e-01  9.799500e-02  3.034850e-01  8.380850e-01
 -1.147305e+00 -8.838050e-01 -2.613000e-02  4.856500e-02 -3.882150e-01
  2.053510e+00  6.011650e-01 -2.663175e-01  3.435400e-01 -9.298150e-01
 -2.343700e-01  1.258950e-01 -1.491650e-01 -4.573615e-01 -6.752050e-01
 -4.088000e-02 -5.184800e-01  2.271900e-01 -4.466850e-01  5.242400e-01
  4.384400e-01 -7.453550e-02 -5.183800e-01 -1.637785e-01 -1.690000e-03]
[-0.478995   0.531375  -0.016625   0.961575  -0.469895  -0.91854
 -0.008925  -0.50664    0.15734    0.3691     0.63389   -0.0539759
 -0.826275   0.2716855  0.6997335  0.4287355  0.4045675  0.39175
 -0.41546    0.19501    0.1614215 -0.0490965 -0.1739065  0.338695
  0.223012  -1.084565  -0.

In [44]:
model["hi"]

array([-0.54313  ,  0.34427  ,  0.27125  ,  1.0487   , -1.1642   ,
       -1.2722   ,  0.35781  , -0.56527  , -0.29879  ,  0.85179  ,
        0.52222  , -0.0019718, -0.46435  ,  0.033631 ,  0.048367 ,
        0.78762  ,  0.075995 ,  0.51577  ,  0.34778  ,  0.53802  ,
        0.28299  , -0.1313   , -0.073753 ,  0.42614  ,  0.030954 ,
       -0.55033  , -0.99789  , -0.28947  ,  0.30517  , -1.1194   ,
        1.2957   ,  0.91165  ,  0.32222  ,  0.93405  , -0.34152  ,
       -0.62713  , -0.092165 ,  0.50901  ,  0.29204  , -0.20122  ,
        0.19614  , -0.45882  ,  1.1099   , -0.68737  ,  1.5724   ,
       -0.10446  ,  0.23594  , -0.56594  ,  0.43676  ,  0.98093  ])

In [165]:
model["world"]

array([-0.41486 ,  0.71848 , -0.3045  ,  0.87445 ,  0.22441 , -0.56488 ,
       -0.37566 , -0.44801 ,  0.61347 , -0.11359 ,  0.74556 , -0.10598 ,
       -1.1882  ,  0.50974 ,  1.3511  ,  0.069851,  0.73314 ,  0.26773 ,
       -1.1787  , -0.148   ,  0.039853,  0.033107, -0.27406 ,  0.25125 ,
        0.41507 , -1.6188  , -0.81778 , -0.73892 , -0.28997 ,  0.57277 ,
        3.4719  ,  0.73817 , -0.044495, -0.15119 , -0.93503 , -0.13152 ,
       -0.28562 ,  0.76327 , -0.83332 , -0.6793  , -0.39099 , -0.64466 ,
        1.0044  , -0.2051  ,  0.46799 ,  0.99314 , -0.16221 , -0.46022 ,
       -0.37639 , -0.67542 ])

In [182]:
np.mean([model[word] for word in preprocess(s2)],axis=0)

array([-0.478995 ,  0.531375 , -0.016625 ,  0.961575 , -0.469895 ,
       -0.91854  , -0.008925 , -0.50664  ,  0.15734  ,  0.3691   ,
        0.63389  , -0.0539759, -0.826275 ,  0.2716855,  0.6997335,
        0.4287355,  0.4045675,  0.39175  , -0.41546  ,  0.19501  ,
        0.1614215, -0.0490965, -0.1739065,  0.338695 ,  0.223012 ,
       -1.084565 , -0.907835 , -0.514195 ,  0.0076   , -0.273315 ,
        2.3838   ,  0.82491  ,  0.1388625,  0.39143  , -0.638275 ,
       -0.379325 , -0.1888925,  0.63614  , -0.27064  , -0.44026  ,
       -0.097425 , -0.55174  ,  1.05715  , -0.446235 ,  1.020195 ,
        0.44434  ,  0.036865 , -0.51308  ,  0.030185 ,  0.152755 ])

In [45]:
##############end Example

In [176]:
#test=pd.to_numeric(df.loc[df[0] == 'good'])
df.loc[df[0] == 'good']

0         1         2         3         4         5         6    \
1040  good -0.605064  0.750338 -0.357561  0.559628  0.372538 -0.225532   

          7         8         9    ...       91        92        93   \
1040  0.20982  0.322781 -0.397406  ...  0.429263 -0.070537 -0.025906   

           94        95        96       97        98        99        100  
1040  0.830147  0.928995  0.628726  0.62987 -0.647675  0.008297  0.498201  

[1 rows x 101 columns]

In [184]:
good=np.array(df.loc[df[0] == 'good'])[0][1:]
good
#good=good.values[0][1:]
good.astype(float)

array([-0.6050638 ,  0.75033778, -0.35756069,  0.55962807,  0.37253818,
       -0.22553228,  0.20982015,  0.32278138, -0.39740622, -0.11251175,
        0.60983092,  0.66415328, -0.6410203 , -0.2465214 ,  0.45571682,
       -1.41686964,  0.93193793,  0.31855482,  0.33465785,  0.28014287,
       -0.22833929,  0.30800176,  0.91108513, -0.14133626,  0.31309778,
        1.16345549,  0.43320203, -1.11014891,  0.81647634,  0.90124726,
        0.88448638,  0.37285435,  0.43028617,  0.9584955 , -0.99939501,
        0.33037791,  0.2496722 , -0.56141979, -0.22573456,  0.76829439,
        0.41068336,  0.1598134 , -0.70986271,  0.47615069,  0.724325  ,
        0.84300834,  0.37968373, -0.49013177,  0.20500499, -0.47323036,
       -0.10184456, -0.10935862, -0.90881866, -0.48304382, -0.17107232,
       -0.44038266,  0.58729094,  0.89631611,  0.53794736,  0.28038544,
       -1.0682838 ,  0.51772404,  0.23506904,  0.07441196, -1.44060099,
        0.65947533, -0.20023557, -0.08428721,  0.29650548,  0.08

In [79]:
nice=df.loc[df[0] == 'nice']
nice=nice.values[0][1:]
nice

array([-0.101442523, 0.02159057, -0.020987113999999998, 0.007815188,
       -0.015625983, -0.019297399, 0.012029203999999998, 0.038401164,
       -0.033532724, 0.025246627999999997, 0.071760833, 0.004723486,
       -0.06430664700000001, -0.069766857, -0.014584428, 0.005106635,
       0.026301585, 0.061814840999999995, -0.000216073, -0.011334997,
       0.026673505, -0.027870715, 0.07990000400000001, -0.104127482,
       0.041412421, 0.013420383999999999, 0.046623662,
       -0.04866097900000001, 0.027697334, 0.054986734, 0.06857717,
       0.041096932999999995, -0.024087077000000002, 0.038593754,
       0.04295142, -0.036289562000000004, 0.022001291, -0.085833609,
       -0.056825195, 0.089307778, 0.06871724900000001, -0.004194206,
       0.013780789, 0.018453179, 0.061971258, 0.001352128, 0.074508622,
       0.006720359, 0.037088364, -0.022473866000000002, -0.063732222,
       -0.0009865289999999999, -0.08406365699999999, -0.047223385,
       -0.014129441999999999, -0.050902598, 0.080

In [80]:
person=df.loc[df[0] == 'person']
person=person.values[0][1:]
person

array([-0.256274402, 0.23023667899999997, -0.15310406699999998,
       0.055703632999999995, -0.14298154400000002, 0.037141968,
       -0.014882237, 0.073190011, 0.12328463, -0.06339205099999999,
       0.38401868899999997, 0.076205507, -0.126037061, -0.202550203,
       -0.056448404, -0.07197158, 0.07448953400000001, 0.164333791,
       0.218306959, 0.003725869, -0.157522663, 0.06502100799999999,
       0.243300483, -0.229703799, 0.16031885099999998, 0.120323636,
       0.075271383, -0.245827198, 0.260144174, 0.15588930199999998,
       0.26125598, 0.035134938, -0.015048252, 0.342265218, 0.070781544,
       0.071990035, -0.034873866, -0.195808366, 0.037973627, 0.30311361,
       0.21651098100000002, 0.039256375, -0.18616454300000002,
       0.089403711, 0.06492006, -0.040624727, 0.270283222,
       0.035481083999999996, 0.197436005, -0.17281222300000001,
       -0.032291226, 0.029469158999999998, -0.283807576,
       -0.13241641199999998, 0.06807664, -0.246887207, 0.178857237,
       

In [86]:
df.loc[df[0] == 'person']

0         1         2         3         4         5         6    \
3514  person -0.256274  0.230237 -0.153104  0.055704 -0.142982  0.037142   

           7        8         9    ...       91        92        93   \
3514 -0.014882  0.07319  0.123285  ... -0.151039 -0.177473 -0.227384   

           94        95        96        97        98        99        100  
3514  0.103789  0.050454  0.097711  0.090239 -0.411961  0.210897 -0.071248  

[1 rows x 101 columns]

In [188]:
ss1="good person"
ss2="nice person"
import scipy
vector_11 = np.mean([df.loc[df[0] == word].values[0][1:].astype(float) for word in preprocess(ss1)],axis=0)
vector_22 = np.mean([df.loc[df[0] == word].values[0][1:].astype(float) for word in preprocess(ss2)],axis=0)
cosine = scipy.spatial.distance.cosine(vector_11, vector_22)
print('similarity between ss1 and ss2 is: ',round((1-cosine)*100,2),'%')
#good person vs research person ==58%


similarity between ss1 and ss2 is:  77.49 %


In [103]:
vector_11 = np.mean([df.loc[df[0] == word].values[0][1:] for word in preprocess(ss1)],axis=0)

In [178]:
vector_11

array([-0.43066909900000006, 0.4902872295, -0.2553323805, 0.307665851,
       0.11477831749999998, -0.094195155, 0.09746895700000001,
       0.1979856975, -0.13706079499999999, -0.087951899,
       0.49692480250000004, 0.3701793925, -0.38352867949999997,
       -0.2245358005, 0.1996342075, -0.74442061, 0.5032137335,
       0.241444305, 0.2764824035, 0.1419343715, -0.192930974,
       0.1865113825, 0.577192806, -0.1855200305, 0.236708313,
       0.6418895609999999, 0.2542367055, -0.6779880525, 0.5383102595,
       0.5285682825, 0.5728711785, 0.20399464500000003, 0.2076189585,
       0.650380358, -0.4643067345, 0.201183971, 0.10739916899999999,
       -0.37861407550000004, -0.0938804675, 0.535704002, 0.3135971725,
       0.0995348895, -0.44801362600000005, 0.2827772015,
       0.39462253049999996, 0.40119180600000004, 0.3249834775,
       -0.22732534100000001, 0.20122049749999998, -0.3230212925,
       -0.06706789149999999, -0.0399447285, -0.5963131190000001,
       -0.307730116, -0.0514